pushover:
  user: ${PUSHOVER_USER}
  token: ${PUSHOVER_TOKEN}

config:
  location: ${CONFIG_LOCATION}
  writer:
    enabled: true

logging:
  level:
    root: INFO
    com:
      github:
        davemeier82: DEBUG

hivemq:
  server:
    host: ${HIVEMQ_SERVER_HOST}
    port: ${HIVEMQ_SERVER_PORT}