notification:
  config:
    location: ${PUSH_NOTIFICATION_CONFIG_LOCATION}
  push:
    enabled: true
    default-sender:
      enabled: true
    translation:
      properties:
        defaultLocale: ${TRANSLATION_DEFAULT_LOCALE:en}

pushover:
  enabled: true
  credentials:
    - user: ${PUSHOVER_USER}
      token: ${PUSHOVER_TOKEN}

device:
  config:
    location: ${CONFIG_LOCATION}
    writer:
      enabled: true

logging:
  level:
    root: INFO
    com:
      github:
        davemeier82: DEBUG

hivemq:
  server:
    host: ${HIVEMQ_SERVER_HOST}
    port: ${HIVEMQ_SERVER_PORT}

influxdb2:
  url: ${INFLUXDB2_URL}
  token: ${INFLUXDB2_TOKEN}
  bucket: ${INFLUXDB2_BUCKET}
  organization: ${INFLUXDB2_ORGANIZATION}

